db:
  host: localhost
  port: 5432
  user: admin
  password: changeme
  dbname: issues

push:
  actions:
    - run: "function1"
      branch: master
      repository: content-gitops
    - run: "action2"
      branch: preprod
      repository: content-gitops

issue:
  actions:
    - run: "saveIssueToDB"
    - run: "addLabel"

issueComment:
  actions:
    - run: "saveComment"
